name: Renovate
on:
  schedule:
    # Run every 15 minutes to check for updates
    - cron: '0/15 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v1
        with:
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          owner: ${{ github.repository_owner }}
          repositories: 'invidious-companion'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.12
        with:
          configurationFile: renovate.json
          token: '${{ steps.get_token.outputs.token }}'
        env:
          RENOVATE_REPOSITORIES: 'unixfox/invidious-companion'